name: Critical Tests

on:
  workflow_dispatch:

env:
  my_user: standard_user
  my_password: secret_sauce

jobs:
  critical:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Run critical tests
        run: npx playwright test --grep @critical